package dev.masterflomaster1.jwa.model;

public enum Meta {

    ALL_MESSAGES,
    AUTH_MANAGER_INFO,
    BABEL,
    FEATURE_USAGE,
    FILE_REPO_INFO,
    GLOBAL_PREFERENCES,
    GLOBAL_RENAME_STATUS,
    GLOBAL_USER_INFO,
    LANGUAGE_INFO,
    NOTIFICATIONS,
    SITE_INFO,
    USER_INFO,
    WIKI_BASE

}
